# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MiniURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_url', models.URLField(max_length=150, unique=True)),
                ('url_code', models.CharField(max_length=15, unique=True)),
                ('create_at', models.DateField(auto_now_add=True)),
                ('identifier_create', models.CharField(blank=True, max_length=50)),
                ('access_number', models.IntegerField(default=0, max_length=11)),
            ],
        ),
    ]
