# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 23:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniurl',
            name='access_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='identifier_create',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='url_code',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
